#! /bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

export DIST_PATH=${DIR}
export BASE_ZIP_IMG=`ls -t ${DIST_PATH}/image/*.{zip,7z,xz} | head -n 1`
export BASE_APT_CACHE=no
export OCTOPI_INCLUDE_WIRINGPI=no
export BASE_IMAGE_RASPBIAN=no
# The root partiton of the image filesystem, 2 for raspbian, 1 for armbian
export BASE_ROOT_PARTITION=1
export BASE_IMAGE_RESIZEROOT=500
export BASE_IMAGE_ENLARGEROOT=1000
export CUSTOM_PI_OS_PATH=$(<${DIR}/custompios_path)
export PATH=$PATH:$CUSTOM_PI_OS_PATH
echo ${CUSTOM_PI_OS_PATH}

${CUSTOM_PI_OS_PATH}/build_custom_os $@
