#!/usr/bin/env bash
# treehouses cube image generation script for CustomPiOS
set -x
set -e

export LC_ALL=C

source /common.sh


unpack /filesystem/home/pi /home/"${BASE_USER}" "${BASE_USER}"
unpack /filesystem/home/root /root root
unpack /filesystem/boot /boot

# /boot/version.txt
version="$DIST_NAME-$DIST_VERSION"
echo "writing version.txt: $version"
echo "$version" > /boot/version.txt

# for kubernetes 
sed -i -e 's#$# cgroup_memory=1 cgroup_enable=memory#' /boot/cmdline.txt

apt update

# in case we are building from a regular raspbian image instead of the lite one...
remove_extra=$(remove_if_installed scratch squeak-plugins-scratch squeak-vm wolfram-engine python-minecraftpi minecraft-pi sonic-pi oracle-java8-jdk bluej libreoffice-common libreoffice-core freepats greenfoot nodered)
echo "removing:" $remove_extra
apt remove -y --purge  $remove_extra
apt autoremove -y

apt install -y --force-yes git screen vim avahi-daemon curl autossh docker.io apt-transport-https

curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
apt update
apt install -y nodejs kubectl kubeadm kubelet

mkdir -p /etc/bash_completion.d
npm i -g @treehouses/cli
mkdir -p /root/.ssh
chmod go-rwx /root/.ssh
treehouses sshkey github adduser dogi
treehouses sshkey github adduser louhdy
treehouses sshkey github adduser lanxel97
treehouses sshkey github adduser wesitos
treehouses sshkey github adduser lmmrssa
cp -R /root/.ssh /home/"${BASE_USER}"
chown -R "${BASE_USER}": /home/"${BASE_USER}"/.ssh

echo " - reinstall iputils-ping"
apt install --reinstall iputils-ping

# disable GUI at start
#systemctl_if_exists disable lightdm.service || true

#cleanup
apt clean
apt autoremove -y

# unpack root again ;)
unpack /filesystem/root /
