name: build cube image

on:
  workflow_dispatch:
  repository_dispatch:
  push:
    branches:
      - "main"
#      - "<branch>"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: install dependencies
      run: |
        sudo apt update
        sudo apt install coreutils p7zip-full qemu-user-static

    - name: checkout CustomPiOS
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
        repository: 'guysoft/CustomPiOS'
        path: CustomPiOS
 
    - name: checkout repository code
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
        path: repository
        submodules: true

    - name: download raspios lite arm64 image
      run: |
        cd repository/src/image-raspios_lite_arm64
        wget -c --trust-server-names 'https://downloads.raspberrypi.org/raspios_lite_arm64/images/raspios_lite_arm64-2024-07-04/2024-07-04-raspios-bookworm-arm64-lite.img.xz'

    - name: update CustomPiOS paths
      run: |
        cd repository/src/image-raspios_lite_arm64
        ../../../CustomPiOS/src/update-custompios-paths
    
    - name: build image
      run: |
        sudo modprobe loop
        cd repository/src
        sudo bash -x ./build_dist raspios_lite_arm64

    - name: copy output
      id: copy
      run: |
        source repository/src/config
        NOW=$(date +"%Y-%m-%d-%H%M")
        IMAGE=$NOW-cube-$DIST_VERSION
        cp repository/src/workspace-raspios_lite_arm64/*.img $IMAGE.img
        gzip $IMAGE.img
        sync; sync; sync
        echo "OUTPUT=$IMAGE" >> $GITHUB_ENV

    - name: upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.OUTPUT }}
        path: ${{ env.OUTPUT }}.img.gz
