name: Build Image

on:
  workflow_dispatch:
  repository_dispatch:
  push:
    branches:
      - "main"
#      - "<branch>"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install coreutils p7zip-full qemu-user-static

    - name: Checkout CustomPiOS
      uses: actions/checkout@v3
      with:
        repository: 'guysoft/CustomPiOS'
        path: CustomPiOS

    - name: Checkout Project Repository
      uses: actions/checkout@v3
      with:
        path: repository
        submodules: true

    - name: Download Raspios Lite ARM64 Image
      run: |
        cd repository/src/variants/raspios_lite_arm64
        wget -c --trust-server-names 'https://downloads.raspberrypi.org/raspios_lite_arm64/images/raspios_lite_arm64-2022-09-26/2022-09-22-raspios-bullseye-arm64-lite.img.xz'

    - name: Update CustomPiOS Paths
      run: |
        cd repository/src/variants/raspios_lite_arm64
        ../../../../CustomPiOS/src/update-custompios-paths
    
    - name: Build Image
      run: |
        sudo modprobe loop
        cd repository/src
        sudo bash -x ./build_dist raspios_lite_arm64

    - name: Copy output
      id: copy
      run: |
        source repository/src/config
        NOW=$(date +"%Y-%m-%d-%H%M")
        IMAGE=$NOW-cube-$DIST_VERSION
        cp repository/src/workspace/*.img $IMAGE.img
        gzip $IMAGE.img
        sync; sync; sync
        echo "::set-output name=image::$IMAGE"

    - uses: actions/upload-artifact@v1
      with:
        name: ${{ steps.copy.outputs.image }}
        path: ${{ steps.copy.outputs.image }}.img.gz
